### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by hsbasu** [mamolinux/sucharu-theme-icon#94]
1. [ ] Actions
    1. [x] Full colour
        1. [x] mail-send-receive.svg
        2. [x] process-stop.svg
        3. [x] system-hibernate.svg
        4. [x] system-lock-screen.svg
        5. [x] system-log-out.svg
        6. [x] system-reboot.svg
        7. [x] system-shutdown.svg
        8. [x] system-suspend.svg
    2. [ ] Symbolic/scalable
2. [ ] Apps
3. [ ] Devices
4. [ ] Places
5. [ ] Colour variants
